# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - git clone https://github.com/JuliaRegistries/General  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "General"))')  
  - git clone https://github.com/SISL/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "SISL"))')  
  - git clone https://github.com/JuliaPOMDP/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "JuliaPOMDP"))')  
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes -e 'import Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("PedestrianAvoidancePOMDP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
